docker_common: &docker_common
  image: plugins/docker
  secrets: [ docker_username, docker_password ]
  repo: metwork/mfxxx-centos7-buildimage
  
trigger_common: &trigger_common
  image: plugins/downstream
  fork: true
  secrets: [ downstream_token, downstream_server ]
  params:
    - FORCED_OS_VERSION=centos7
  

pipeline:
  docker_master:
    <<: *docker_common
    build_args:
      - BRANCH=master
    tags:
      - latest
      - master
    when:
      branch: master
      event: push
  docker_integration:
    <<: *docker_common
    build_args:
      - BRANCH=integration
    tags:
      - integration
    when:
      branch: integration
      event: push
  docker_other:
    <<: *docker_common
    build_args:
      - BRANCH=master
    tags:
      - ${DRONE_BRANCH}
    when:
      event: push
      branch:
        exclude: [ master, integration ]
  slack:
    image: plugins/slack
    channel: dev
    username: drone
    secrets: [ slack_webhook ]
    when:
      status: [ failure ]
      event: push
      branch: [ master, integration ]
  trigger_master:
    <<: *trigger_common
    repositories:
      - metwork-framework/mfserv@master
    when:
      status: [ success ]
      event: push
      branch: master
  trigger_integration:
    <<: *trigger_common
    repositories:
      - metwork-framework/mfserv@integration
    when:
      status: [ success ]
      event: push
      branch: integration
