trigger_common: &trigger_common
  image: plugins/downstream
  fork: true
  secrets: [ downstream_token, downstream_server ]
  params:
    - FORCED_OS_VERSION=centos7
  

pipeline:
  docker:
    image: metwork/drone-docker-specific-image:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root:/root
    commands:
      - if test "${DRONE_BRANCH}" = "master"; then
          docker build -t metwork/mfxxx-centos7-buildimage:master -t metwork/mfxxx-centos7-buildimage:latest --build-arg BRANCH=master --build-arg CACHEBUST=${DRONE_BUILD_NUMBER} .;
        elif test "${DRONE_BRANCH}" = "integration"; then
          docker build -t metwork/mfxxx-centos7-buildimage:integration --build-arg BRANCH=integration --build-arg CACHEBUST=${DRONE_BUILD_NUMBER} .;
        else
          docker build -t metwork/mfxxx-centos7-buildimage:${DRONE_BRANCH} --build-arg BRANCH=master --build-arg CACHEBUST=${DRONE_BUILD_NUMBER} .;
        fi
      - docker push metwork/mfxxx-centos7-buildimage:${DRONE_BRANCH}
      - if test "${DRONE_BRANCH}" = "master"; then docker push metwork/mfxxx-centos7-buildimage:latest; fi
    when:
       event: push 
  trigger_master:
    <<: *trigger_common
    repositories:
      - metwork-framework/mfserv@master
      - metwork-framework/mfdata@master
    when:
      status: [ success ]
      event: push
      branch: master
  trigger_integration:
    <<: *trigger_common
    repositories:
      - metwork-framework/mfserv@integration
      - metwork-framework/mfdata@integration
    when:
      status: [ success ]
      event: push
branch: integration
